pipeline {
    agent any

    stages {
        stage('Build') {
    steps {
        sh 'chmod +x hello.cpp'
        sh 'g++ hello.cpp -o output'
    }
}

        stage('Test') {
            steps {
                sh './output'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment Successful'
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
